name: Zamora-Workflow

on:
  push:
    branches:
      - zamora

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Runner Notification Zamora 2
        run: echo "Deploy to Production"